name: Checkout_workspace

on: workflow_dispatch
jobs:
  checkout_respistory
    runs-on: ubuntu-20.04
    steps:
      - name: Chekout repository
        uses: actions/checkout@v3
      - name: show workspace
        run: |
            dir